apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
patches:
  - patch: |
      - op: replace
        path: /spec/prune
        value: false
    target:
      kind: Kustomization
      name: flux-system
